Hapag-Lloyd/terraform-aws-bastion-host-ssm

.github/workflows/pull-request.yml, .gitignore, README.md, examples/full/README.md, examples/full/main.tf, examples/full/provider.tf, examples/simple/provider.tf, main.tf, variables.tf
This PR activates the schedule mechanism of the autoscaling group. The instance is started/stopped at the specified time. To activate scheduling add the `schedule` object to the module definition. As the instances are shut down for some hours, cost savings can be realized.
```hcl
module "bastion_host" {
...
schedule = {
start = "0 9 * * MON-FRI"
stop  = "0 17 * * MON-FRI"
}
}
```
Due to the `time_zone` attribute the minimum version of the `aws` provider has been raised to `3.53.0`
My code follows the style guidelines of this project
=> feat: add schedule to autoscaling group

.pre-commit-config.yaml, README.md, examples/full/main.tf, locals.tf, main.tf, variables.tf
Introduces settings for generating resource names within the module to better match several company guidelines. Use the new variable `resource_names` to set a common prefix and the separator character used that should be used within the resource names.
```hcl
module "bastion" {
...
resource_names = {
prefix = "deve-bastion"
separator = "-"
}
}
```
The variable `resource_prefix` is gone. Move the value to the `resource_names` key `prefix` as shown above.
Created a plan of the `full` example and checked the resource names.
=> feat: make resource names configurable

.github/dependabot.yml
Dependabot should not update the examples or the providers of the main module. We specify the minimum version which can be used to apply the module. Thus we do not need to update anything.
The examples should always run with the minimum versions to make sure that the module is still deployable with them when the source was changed.
None.
=> chore: do not update dependencies by Dependabot

.github/workflows/pull-request.yml, README.md, scripts/export_aws_credentials_from_keypass.sh
This PR adds a simple script to retrieve the AWS credentials for a user from Keepass.
No verification done. Just a little helper script
=> feat: add script to read AWS credentials from Keepass

.gitignore, README.md, examples/full/main.tf, examples/simple/main.tf, main.tf, role.tf, variables.tf
This PR adds the policies needed to connect to the Bastion. It also introduces a role which can be assumed by an IAM user.
Fill the `iam_user_arn` with the ARN of the user which should be allowed to connect to the Bastion host.
Deployed the `full` example and connected to the Bastion host.
=> feat: add role and policies

.github/workflows/tfsec.yml
Skip the TFSec run on `main` branch. This is superfluous as every PR is based on the latest `main` branch and TFSec runs for the PR.
None.
=> ci: skip TFSec for pushes on main branch

README.md, main.tf
If schedules are used the bastion is not running outside the business hours. This PR adds a launch template to have an easy way to start a bastion host from the AWS Console.
=> feat: add launch template for manual start

README.md, examples/full/main.tf, main.tf, variables.tf
30% of the monthly costs were due to EC2 instance monitoring. This PR disables the monitoring by default. You can enable it by setting `instance.enable_monitoring` to `true`.
Variables have been restructured. See paragraph below.
A new block `instance` has been introduced. Move the `instance_type` to `instance.type` and `root_volume_size` to `instance.root_volume_size`.
```hcl
module "bastion" {
...
instance = {
type              = "t3.nano"
root_volume_size  = 8
}
```
=> feat: make the EC2 monitoring configurable

README.md
Fix the documentation as spot instances are no longer planned but implemented.
None
=> docs: fix doc as spot instances are implemented

main.tf
Add the `subnet_id` to the launch template to make usage via AWS Console easier.
=> fix: add subnet id to manual launch template

main.tf
Reverts Hapag-Lloyd/terraform-aws-bastion-host-ssm#42
=> revert: "fix: add subnet id to manual launch template"

README.md, provider.tf
It's a module and we do not configure any providers here. Remove the provider settings from `provider.tf`.
None
=> fix: remove hard coded provider statement

autoscaling.tf
Use the `name_prefix` of the `aws_autoscaling_group` as the new resource is created before the old one is deleted. This results in a duplicate key error during apply if `name` is used.
=> fix: use name_prefix for autoscaling groups

README.md, examples/full/main.tf, examples/simple/main.tf, examples/spot/main.tf, role.tf, variables.tf
Allow more than one single user to connect to the Bastion host. `iam_user_arns` holds a list of ARNs to become principal of the connection role.
Rename `iam_user_arn` to `iam_user_arns`. It holds a list of user arns now.
=> feat: allow multiple users to connect

.github/workflows/pull-request.yml, scripts/bastion_services.json, scripts/connect_bastion.sh
- extract the service to connect to to a separate file as this differs from user to user and shouldn't be mixed with the code
- allow services in different regions
- allow different bastion host names and connection role names in different accounts/environments
- fix several shell issues
- add documentation to the services Json file
- use keep alive to leave the SSH connection opened. Otherwise it is closed after 20 minutes
If you described your services within the shell script, move it to the `bastion_services.json` file.
Checked the script on my local machine.
=> feat: improve connection script

README.md, autoscaling.tf, locals.tf, main.tf
Adds `Name` and `bastion-access` tags to the launch template to enforce these tags at the started instance. Otherwise the script can't connect as it does not find any bastion host.
The plan for the `spot` example looks good.
=> fix: add tags to the manual launch template

README.md, examples/full/main.tf, main.tf, variables.tf
As described in #78, `aws_ami_copy` needs the ARN and not the ID of the KMS key. Quite confusing as the resource has a `key_id` attribute.
This PR replaces the module variable `kms_key_id` by `kms_key_arn`.
Closes #78
`kms_key_id` has been replaced with `kms_key_arn`. The module needs the ARN of your KMS key and no longer the id.
=> fix!: replace KMS key id with key ARN

.github/FUNDING.yml
Displays the current sponsors of the project on the GitHub project page.
Not needed. No code change.
=> chore: show project sponsors

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds templates for bug and feature issues to make sure that all relevant information is given when submitting the issue.
Templates only. No verification needed.
=> chore: add issue templates for bugs and features

.github/dependabot.yml
Dependabot should update used Terraform modules with `fix(deps)` in the PR title as these changes are user relevant. Without a `fix` nothing is released.
Not needed. No code change.
=> ci: update used Terraform modules with a `fix` PR

.github/workflows/pull-request-lint.yml
Disables the check to validate the commit message instead of the PR title. This repository uses the whole PR as commit message, so it makes no sense to validate the commit of the feature branch. This prevents the action from failing if there is one commit only.
Not needed. CI change only.
=> ci: do not validate single commit message

.github/workflows/release.yml
Removes the superfluous setting for Release-Please which overrides the next version number of this module. Version numbers are detected automatically by the action.
Not needed. CI change only.
=> ci: do not set the next release version

main.tf, variables.tf
Adds the new optional variable `ami_name__filter` which selects the AMI for the bastion host. Uses `amzn2-ami-hvm-*-x86_64-ebs` as default.
Not done.
=> feat: add filter for AMI name

.github/workflows/pull-request-lint.yml, .github/workflows/pull-request.yml
This PR skips the workflows designated for feature branches in the release branch.
Not needed. CI change only.
=> ci: do not run feature branch workflows in release branch

.github/workflows/pull-request-lint.yml, .github/workflows/pull-request.yml
Fixes the branch ignore rule for workflows to exclude the release branches.
Not needed. CI only.
=> ci: fix `branches-ignore` rule for feature branch workflows

main.tf
Searches for the bastion AMI not only in the global Amazon account but also in the user's account. This allows to use a self-build custom AMI.
=> feat: search for AMIs in current account

.github/workflows/pull-request-lint.yml
The `main` scope is used by Release-Please for releases of the `main` branch. Thus this scope should be allowed.
Not done as it is a CI change only.
=> ci: allow semantic commit scope `main`

examples/full/main.tf, locals.tf, main.tf, variables.tf
Sometimes the caller of the module has already an instance profile available or wants to use the default profile created by AWS (`AmazonSSMRoleForInstancesQuickSetup`). The name of the IAM role can be given to the module via `var.instance["profile_name"]`.
Not done.
=> feat: allow user defined instance profile

main.tf
The instance profile was created if a user defined profile was given. This has been inverted.
Not done
=> fix: create instance profile if no profile specified

.github/workflows/new-pr-opened.yml
Removes the welcome message from Dependabot PRs. It never worked as the `GITHUB_TOKEN` is created with read-only permissions and the workflow fails.
=> ci: suppress welcome message for Dependabot PRs

.github/workflows/new-pr-opened.yml
Javascript comments should start with `//`. `#` does not work and results in strange error messages from the action.
=> ci: fix Javascript comment character

main.tf
This PR reduces the hop_limit of the IMDS token to 1. This is a bastion host used for port forwarding only. There shouldn't be any jobs running.
Reason: The token should not leave the machine and we do not use Docker here (needs a hop_limit of at least 2).
=> fix: set token hop_limit to 1

.github/workflows/slash_ops_commands.yml
Fixes the processing of `/help` by adding the correct PR number to the action. This way the comment can be added and a maintainer informed.
=> ci: fix the issue number to add comment for `/help` command

examples/full/locals.tf, examples/full/main.tf, examples/full/vpc.tf, examples/simple/locals.tf, examples/simple/main.tf, examples/simple/vpc.tf, examples/spot/locals.tf, examples/spot/main.tf, examples/spot/vpc.tf, main.tf
Adds the missing VPC endpoints in the examples. Applying the examples was working technically but they were useless as you were not able to establish a connection to the bastion host.
Fixes #141 
All examples have been applied. Connection to the bastion host is possible.
=> docs: add VPC endpoints to examples

renovate.json
Activates Renovate by adding a `renovate.json` file. We rely on the default Hapag-Lloyd settings. The Renovate job is started somewhere else.
=> chore: activate Renovate dependency updates

.config/tflint.hcl, .github/workflows/pull-request.yml, .github/workflows/terraform-tfsec.yml, .github/workflows/terraform.yml, examples/cost/README.md, examples/cost/locals.tf, examples/cost/main.tf, examples/cost/provider.tf, examples/cost/vpc.tf, examples/spot/main.tf, locals.tf, variables.tf
Adds the Hapag-Lloyd standard Terraform module workflow to the project. Currently supports TfSec, TfLint and a simple validate.
Workflow ran in this project.
=> ci: use standard workflow for Terraform

autoscaling.tf
Remove enable_spot condition in aws_autoscaling_schedule.down, does not make sense here.
=> fix: scale spot instances down if a schedule exists

.github/workflows/terraform.yml
This PR uses the secrets provided by the GitHub organization to access a cloud account to be able to use TfLint. The hardcoded credentials weren't working any longer.
The workflow ran on this PR. It failed before.
=> ci: allow TfLint cloud access via pre-deployed role

.github/workflows/terraform.yml, examples/cost/main.tf, examples/full/main.tf, examples/simple/main.tf, examples/spot/main.tf, locals.tf, main.tf, panic-button-off.tf, panic-button-on.tf, provider.tf, terraform.tf, variables.tf
The infrastructure should be immutable, i.e. applying the same infrastructure every week shouldn't change anything. At the moment the AMI id changes when a new AMI is published. This might introduce problems as the image is changed. It also increases the elapsed time of your workflows/pipelines by roughly 4 minutes.
This PR adds an optional `var.ami_id`. In case it is filled, this AMI is used for the Bastion EC2 instance. The `var.ami_name_filter` is now deprecated and will be removed with version 3.0.0 of the module.
I recommend using this new parameter. But make sure that you have an update procedure in place to update the AMI id regularly.
Apply the `simple` example --> Bastion host is setup and boots
=> feat: add `var.ami_id` to fix the AMI used for the Bastion

.github/workflows/renovate-auto-approve.yml
Uses the new PAT `secrets.PAT_FOR_PR_AUTO_APPROVAL` to approve Renovate PRs. Temporary created access tokens via GitHub App do not work here as the app is not a valid approver.
To use the auto-merge feature, make sure that the owner of the PAT is in the list of approvers.
=> chore: use PAT to auto-approve Renovate PRs

panic-button-on.tf, role.tf
Using the panic button lambdas ended with `prod-platform-bastion-panic-button-on is not authorized to perform: autoscaling:BatchDeleteScheduledAction`. This PR adds the policy to the role to allow the lambda working
Manually verified in HL environment.
=> fix: allow panic lambdas to modify autoscaling schedule

.github/CODEOWNERS, CODEOWNERS
Use the QCM team as code-owner instead of single members. Allows our Bot to automatically confirm pull requests.
=> ci: set up team as codeowner

.config/cspell.json, panic-button-off.tf, panic-button-on.tf, variables.tf
I have introduced a new variable `log_group_retention_days` to make the retention time of the log-group configurable.
Reason:
```Logging is a crucial aspect of maintaining a secure and reliable environment in systems. Logs can provide valuable insights into system operations, errors, access, usage patterns and potential security incidents. If a log group in CloudWatch is not configured to retain logs for a certain period of time, important data could be lost. In some cases, regulations and standards may also require logs to be retained for specific periods. Failing to retain logs for at least one year could hinder system troubleshooting, vulnerability detection, auditing, and compliance verification.```
=> feat: add variable to make log-group retention configurable

.config/cspell.json, autoscaling.tf, examples/cost/main.tf, examples/full/main.tf, locals.tf, main.tf, panic-button-off.tf, panic-button-on.tf, variables.tf
The `aws_launch_configuration` is deprecated and replaced by `aws_launch_template`. This PR replaces the deprecated resources and combines the on-demand and spot settings into one launch template.
Fixes #383 
Depending on the AMI used, you have to set the `var.instance.root_device_name`. We use `/dev/xvda` as default, which should work for Linux instances.
=> chore!: remove launch configuration

README.md, panic-button-off.tf, panic-button-on.tf, variables.tf
Adds `create_panic_switches` to disable all resources related to the Lambda panic switches. In case they are not needed, e. g. the bastion runs 24/7, there is no need to create these resources.
Fixes #401 
Plan was created and checked against the development account.
=> feat: add a variable to disable the panic switches

locals.tf, main.tf, variables.tf
Simplify the code and move the default AMI id to the declared variable.
None.
=> refactor: move default AMI id to variables

locals.tf, main.tf
The tags of the `aws_autoscaling_group` require an additional setting `propagate_at_launch`. Thus the default tags from the provider are not automatically used.
This PR reads the default tags and adds them with `propagate_at_launch = true`. Usually needed to comply with tagging strategies.
=> fix: add provider default tags to autoscaling group
